import TicketIcon from "lucide-solid/icons/ticket";
import { lookupId } from "../../core/lookups/lookup";
import { defineEntity, entityId } from "../../core/entities/entity-description";
import { generateKsuid } from "../../core/entities/ksuid";

/** Test-only entity fixture. Production definitions are loaded from model-info. */
export const ticketEntity = defineEntity({
  id: entityId("tickets"),
  tableName: "tickets",
  label: "Ticket",
  labelTemplate: "${key}: ${title}",
  pluralLabel: "Tickets",
  icon: TicketIcon,
  identityAttribute: "id",
  attributes: [
    {
      id: "id",
      label: "ID",
      description: "Immutable ticket identifier.",
      valueType: "string",
      create: { hidden: true, initialValue: generateKsuid },
    },
    {
      id: "key",
      label: "Key",
      description: "Human-readable project-prefixed ticket key.",
      generated: true,
      valueType: "string",
      table: { visibleByDefault: true, width: 120 },
    },
    {
      id: "creation_date",
      label: "Created",
      description: "Server-assigned creation date and time.",
      generated: true,
      valueType: "string",
      optional: true,
      table: { visibleByDefault: false, width: 190, type: "date" },
    },
    {
      id: "update_date",
      label: "Updated",
      description: "Server-assigned last-change date and time.",
      generated: true,
      valueType: "string",
      optional: true,
      table: { visibleByDefault: false, width: 190, type: "date" },
    },
    {
      id: "project_id",
      label: "Project",
      description: "Project that owns the ticket.",
      valueType: "string",
      lookup: lookupId("projects"),
      facet: true,
      table: { visibleByDefault: true, width: 140 },
      edit: { control: "lookup", required: true },
      create: { control: "lookup", required: true },
    },
    {
      id: "title",
      label: "Title",
      description: "Short summary of the issue or task.",
      valueType: "string",
      table: { visibleByDefault: true, width: 260 },
      edit: { control: "text", required: true },
      create: { required: true },
    },
    {
      id: "status",
      label: "Status",
      description: "Current workflow state of the ticket.",
      valueType: "string",
      facet: true,
      table: { visibleByDefault: true, width: 120 },
      create: { hidden: true, initialValue: "open" },
    },
    {
      id: "assignee",
      label: "Assignee",
      description: "User currently responsible for the ticket.",
      valueType: "string",
      lookup: lookupId("users"),
      facet: true,
      optional: true,
      table: { visibleByDefault: true, width: 160 },
      edit: { control: "lookup" },
      create: { control: "lookup" },
    },
    {
      id: "description",
      label: "Description",
      description: "Detailed issue or task description.",
      valueType: "string",
      table: { visibleByDefault: true },
      edit: { control: "html" },
      create: {},
    },
  ],
});
