import { defineGenerator } from "../generation/generated-file.ts";
import type { NamedTypeDefinition, TypeDefinition } from "../model/definitions.ts";
import { assertUniqueNames, pascalCase, snakeCase } from "./naming.ts";
import { source } from "./source-template.ts";

const rustKeywords = new Set([
  "as",
  "async",
  "await",
  "break",
  "const",
  "continue",
  "crate",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "union",
  "unsafe",
  "use",
  "where",
  "while",
]);

function rustIdentifier(id: string): string {
  const identifier = snakeCase(id);
  return rustKeywords.has(identifier) ? `r#${identifier}` : identifier;
}

function typeName(type: TypeDefinition): string {
  if (type.kind === "builtin")
    return { boolean: "bool", integer: "i64", json: "serde_json::Value", string: "String" }[type.name];
  if (type.kind === "optional") return `Option<${typeName(type.value)}>`;
  if (type.kind === "list") return `Vec<${typeName(type.value)}>`;
  return pascalCase(type.id);
}

function docs(description: string): string {
  return description
    .split("\n")
    .map((line) => `/// ${line}`)
    .join("\n");
}

function renderType(type: NamedTypeDefinition): string {
  const name = pascalCase(type.id);
  if (type.kind === "alias")
    return source`
      ${docs(type.description)}
      pub type ${name} = ${typeName(type.type)};
    `;
  if (type.kind === "enum") {
    assertUniqueNames(
      type.values.map((value) => value.id),
      `Variants of ${type.id}`,
      pascalCase,
    );
    const values = type.values
      .map(
        (value) => `    ${docs(value.description)}
    #[serde(rename = ${JSON.stringify(value.id)})]
    ${pascalCase(value.id)},`,
      )
      .join("\n");
    return source`
      ${docs(type.description)}
      #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
      pub enum ${name} {
        ${values}
      }
    `;
  }
  assertUniqueNames(
    type.fields.map((field) => field.id),
    `Fields of ${type.id}`,
    snakeCase,
  );
  const fields = type.fields
    .map(
      (field) => `    ${docs(field.description)}
    pub ${rustIdentifier(field.id)}: ${typeName(field.type)},`,
    )
    .join("\n");
  return source`
    ${docs(type.description)}
    #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
    pub struct ${name} {
      ${fields}
    }
  `;
}

export default defineGenerator({
  id: "rust",
  label: "Rust",
  description: "Generate Rust serde API data types and command constants.",
  generate(model) {
    assertUniqueNames(
      model.types.map((type) => type.id),
      "Type declarations",
      pascalCase,
    );
    assertUniqueNames(
      model.commands.map((command) => command.id),
      "Command constants",
      (id) => `${snakeCase(id).toUpperCase()}_COMMAND`,
    );
    assertUniqueNames(
      model.commands.map((command) => command.request.id),
      "Command request types",
      pascalCase,
    );
    const types = model.types.map(renderType).join("\n\n");
    const commandImplementations = model.commands
      .map(
        (command) => source`
          impl Command for ${pascalCase(command.request.id)} {
              const NAME: &'static str = ${JSON.stringify(command.id)};
              const DESCRIPTION: &'static str = ${JSON.stringify(command.description)};
              type Response = ${typeName(command.response)};
          }
        `,
      )
      .join("\n\n");
    const commandDescriptors = model.commands
      .map(
        (command) => source`
          CommandDescriptor::of::<${pascalCase(command.request.id)}>(),
        `,
      )
      .join("\n");
    return [
      {
        relativePath: "api.rs",
        format: "rust",
        contents: source`
          // Generated by joi-codegen. Do not edit.

          use serde::{Deserialize, Serialize};

          use crate::command::{Command, CommandDescriptor};

${types}

          ${commandImplementations}

          pub const COMMAND_DESCRIPTORS: &[CommandDescriptor] = &[
              ${commandDescriptors}
          ];
        `,
      },
      {
        relativePath: "mod.rs",
        format: "rust",
        contents: source`
          // Generated by joi-codegen. Do not edit.

          pub mod api;
        `,
      },
    ];
  },
});
