import { defineGenerator } from "../generation/generated-file.ts";
import type { NamedTypeDefinition, TypeDefinition } from "../model/definitions.ts";
import { assertUniqueNames, camelCase, pascalCase } from "./naming.ts";

function typeName(type: TypeDefinition): string {
  if (type.kind === "builtin") return { boolean: "boolean", integer: "number", string: "string" }[type.name];
  if (type.kind === "optional") return `${typeName(type.value)} | null`;
  if (type.kind === "list") return `readonly ${typeName(type.value)}[]`;
  return pascalCase(type.id);
}

function doc(description: string): string {
  return `/** ${description.replaceAll("*/", "* /")} */`;
}

function renderType(type: NamedTypeDefinition): string {
  const name = pascalCase(type.id);
  if (type.kind === "alias") return `${doc(type.description)}\nexport type ${name} = ${typeName(type.type)};`;
  if (type.kind === "enum") {
    return `${doc(type.description)}\nexport type ${name} = ${type.values.map((value) => JSON.stringify(value.id)).join(" | ")};`;
  }
  assertUniqueNames(
    type.fields.map((field) => field.id),
    `Fields of ${type.id}`,
    camelCase,
  );
  const fields = type.fields
    .map((field) => `  ${doc(field.description)}\n  readonly ${camelCase(field.id)}: ${typeName(field.type)};`)
    .join("\n");
  return `${doc(type.description)}\nexport interface ${name} {${fields ? `\n${fields}\n` : ""}}`;
}

export default defineGenerator({
  id: "typescript",
  label: "TypeScript",
  description: "Generate TypeScript API data types and command mappings.",
  generate(model) {
    assertUniqueNames(
      model.types.map((type) => type.id),
      "Type declarations",
      pascalCase,
    );
    const types = model.types.map(renderType).join("\n\n");
    const requests = model.commands
      .map((command) => `  readonly ${JSON.stringify(command.id)}: ${typeName(command.request)};`)
      .join("\n");
    const responses = model.commands
      .map((command) => `  readonly ${JSON.stringify(command.id)}: ${typeName(command.response)};`)
      .join("\n");
    return [
      {
        relativePath: "api.ts",
        format: "typescript",
        contents: `// Generated by joi-codegen. Do not edit.\n\n${types}\n\nexport interface CommandRequests {\n${requests}\n}\n\nexport interface CommandResponses {\n${responses}\n}\n`,
      },
    ];
  },
});
