[workspace]
members = [
    "examples/joix",
    "examples/joix-codevette",
    "examples/joix-tickets",
    "libs-rust/joi-base",
    "libs-rust/joi-error",
    "libs-rust/joi-plugin",
    "libs-rust/joi-server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

# Run workspace crates and dependencies with release-level optimizations in dev.
[profile.dev]
opt-level = 3
debug = 0
debug-assertions = false
overflow-checks = false
codegen-units = 16
incremental = false
