[workspace]
members = [
    "examples/joix",
    "examples/joix-codevette",
    "examples/joix-tickets",
    "libs-rust/joi-base",
    "libs-rust/joi-error",
    "libs-rust/joi-plugin",
    "libs-rust/joi-server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
