[package]
name = "joi-api-generator"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Generate source code from abstract API descriptions"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.12"

[lib]
path = "src/lib.rs"

[[bin]]
name = "joi-api-docs-server"
path = "src/bin/joi_api_docs_server.rs"
