[package]
name = "joix-tickets"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Integration testbed for JOI libraries"
publish = false

[dependencies]
joi-base = { path = "../../libs-rust/joi-base" }
joi-error = { path = "../../libs-rust/joi-error" }
joi-plugin = { path = "../../libs-rust/joi-plugin" }
joi-server = { path = "../../libs-rust/joi-server" }
ksuid = "0.2"
