use joi_server::{
    data_store::{
        AttributeName, ColumnDataType, ColumnDescription, TableDescription,
        TableDescriptionProvider, TableName,
    },
    generated::api::{ModelControl, ModelPresentation},
    model_metadata::{field, timestamp},
};

/// Canonical wiki model. Attribution and timestamps are generated by mutation contributors.
pub struct WikiPageTableDescriptionProvider;

impl TableDescriptionProvider for WikiPageTableDescriptionProvider {
    fn table_description(&self) -> TableDescription {
        let column = |name: &str, description: &str, data_type| ColumnDescription {
            name: AttributeName(name.into()),
            description: description.into(),
            data_type,
            optional: false,
        };
        TableDescription {
            name: TableName("wikipages".into()),
            discoverable: true,
            columns: vec![
                column(
                    "id",
                    "Immutable KSUID page identifier",
                    ColumnDataType::String,
                ),
                column("title", "Page title", ColumnDataType::String),
                column(
                    "creator",
                    "Original creator (or system for automated writes)",
                    ColumnDataType::Reference {
                        entity: TableName("users".into()),
                    },
                ),
                column(
                    "authors",
                    "Distinct contributing users, in first-contribution order",
                    ColumnDataType::ReferenceList {
                        entity: TableName("users".into()),
                    },
                ),
                column(
                    "creation_date",
                    "Time the page was created",
                    ColumnDataType::String,
                ),
                column(
                    "update_date",
                    "Time the page was last changed",
                    ColumnDataType::String,
                ),
                column(
                    "content",
                    "Rich-text page content stored as HTML",
                    ColumnDataType::Text,
                ),
            ],
            presentation: Some(ModelPresentation {
                route: Some(joi_server::model_metadata::entity_route("wikipage", "id")),
                label: "Wiki page".into(),
                plural_label: "Wiki pages".into(),
                label_template: "${title}".into(),
                icon: "book-open".into(),
                fields: vec![
                    field("id", "ID").ksuid(),
                    field("title", "Title")
                        .edit(ModelControl::Text)
                        .required()
                        .column(true, Some(320)),
                    field("creator", "Creator").column(true, Some(180)).facet(),
                    field("authors", "Authors").column(true, Some(240)).facet(),
                    timestamp("creation_date", "Created"),
                    timestamp("update_date", "Updated").column(true, Some(190)),
                    field("content", "Content")
                        .edit(ModelControl::Html)
                        .column(false, Some(320)),
                ],
            }),
        }
    }
}
